name: linux
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container: python
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source script-linux.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
      with:
        sudo: false
  container:
    runs-on: ubuntu-latest
    container: python:3.8.6
    steps:
      - run: |
          python -m pip install requests
          python -c "import requests;a=requests.get('https://gist.github.com/naveen521kk/8e986f335716aff08a11b3870376e609/raw/2d00d4344252a83db8f49b44214e3e103f5cbffe/text2svg.py');b=open('some.py','wb');b.write(a.content)"          
          python -m pip install pip
          python -m pip install text2svg
          python some.py
      - uses: actions/upload-artifact@v2
        with:
          name: out
          path: hello.svg
