name: linux
on: 
  workflow_dispatch:
  push:
defaults:
  run:
    shell: bash

jobs:
  container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cont: [python:3.8.6,python:3.6.7,python:3.9.1]
    container: ${{matrix.cont}}
    steps:
      - run: |
          python -m pip install requests
          python -c "import requests;a=requests.get('https://github.com/naveen521kk/manimpango/releases/download/v0.0.2/wheels-linux.zip');b=open('linux.zip','wb');b.write(a.content)"          
          7z x linux.zip -obuild
          python -m pip install --find-links $PWD/build manimpango
          python -c "import manimpango"
  
